name: ZKSync Integration Test
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  Test:
    runs-on: ubuntu-latest
    environment: Test

    steps:
      - uses: actions/checkout@v4

      # Ethereum Setup
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Forge
        run: |
          cd contracts/ethereum
          forge install
      
      # - name: Install Ethereum foundry
      #   run: |
      #     make install-ethereum-foundry

      # ZKSync Setup
      - name: Install ZKSync libraries
        run: |
          cd ./contracts/zksync/ && yarn install

      # Run Dockerized L1-L2
      - name: Setup Dockerized L1-L2
        run: |
          export ETHERSCAN_API_KEY=${{vars.ETHERSCAN_API_KEY}}
          echo startung dockerized setup
          git clone https://github.com/matter-labs/local-setup.git
          echo git cloned, starting:

          cd local-setup
          ./start.sh & > /dev/null
          cd ..

          echo starting sleep 100
          sleep 100
          echo done sleep 100, running make-test-integration
          make zksync-test-integration

# export ETHERSCAN_API_KEY=${{vars.ETHERSCAN_API_KEY}}
# source ./.github/workflows/zksync-scripts/ci.env.test
# echo sourced

# # Build Ethereum Contract
# - name: Build Ethereum Contract
#   run: |
#     make ethereum-build

# # Build Starknet Contract
# - name: Build ZKSync Contract
#   run: |
#     make zksync-build

#zksync-test-integration:
# @make ethereum-build && make zksync-build && \
# . ./contracts/ethereum/test/.env.test && . ./contracts/zksync/test/.env.test && \
# . ./contracts/ethereum/deploy.sh && \
# . ./contracts/zksync/deploy.sh && \
# . ./contracts/ethereum/set_zksync_escrow.sh && \
# . ./contracts/zksync/test/set_order.sh && \
# . ./contracts/zksync/test/transfer.sh && \
# . ./contracts/zksync/test/claim_payment.sh

      # # Deploy PaymentRegistry, Escrow, set escrow, and test complete flow
      # - name: Deploy and test complete flow
      #   run: |
      #     make zksync-test-integration
